name: statquickie
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - streamlit
  - pandas
  - numpy
  - matplotlib
  - openpyxl
  - xlrd
  - plotly
  - scikit-learn
  - scipy
  - lightgbm